id: AD14BFCB6
title: 'The Fulfilment of All Aims and Wishes: An Aspiration to Request the Safeguarding
  of Happiness in Tibet'
type: translation
pechas:
- I0191B078
- I50051BCB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:31.465728
  last_modified_at: 2023-01-04 12:07:31.465733
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I0191B078/848B: EBFE
  I50051BCB/D378: EBFE
